package sailpoint.common;

public class RACFAttribute {

	// List of all Out of the Box Mainframe Attributes... this should be
	// referred and not the actual attribute name....

	public static final String USER_ID = "USER_ID";
	public static final String UG_DEF = "UG_DEF";
	public static final String USER_OE_PR = "USER_OE_PR";
	public static final String RACF_GROUPS = "groups"; // This is multi-valued..
	public static final String DCERT_SERIAL_1 = "DCERT.SERIAL.1";
	public static final String DCERT_CREATE_DATE_1 = "DCERT.CREATE_DATE.1";
	public static final String DCERT_OWNER_1 = "DCERT.OWNER.1";
	public static final String DCERT_SERIAL_NUMBER_1 = "DCERT.SERIAL_NUMBER.1";
	public static final String DCERT_ISSUER_NAME_1 = "DCERT.ISSUER_NAME.1";
	public static final String DCERT_TRUST_1 = "DCERT.TRUST.1";
	public static final String DCERT_SUBJECT_NAME_1 = "DCERT.SUBJECT_NAME.1";
	public static final String DCERT_VALID_NOT_BEFORE_1 = "DCERT.VALID_NOT_BEFORE.1";
	public static final String DCERT_VALID_NOT_AFTER_1 = "DCERT.VALID_NOT_AFTER.1";
	public static final String WORKATTR_WAACCNT = "WORKATTR.WAACCNT";
	public static final String RESTRICTED = "RESTRICTED";
	public static final String NOPASSWORD = "NOPASSWORD";
	public static final String TSO_SIZE = "TSO.SIZE";
	public static final String TSO_MAXSIZE = "TSO.MAXSIZE";
	public static final String CICS_OPIDENT = "CICS.OPIDENT";
	public static final String AUTHORITY = "AUTHORITY";
	public static final String ADSP = "ADSP";
	public static final String CATEGORY = "CATEGORY"; // Multi-valued...
	public static final String CLAUTH = "CLAUTH"; // Multi-Valued
	public static final String DATA = "DATA";
	public static final String GRPACC = "GRPACC";
	public static final String INTERVAL = "INTERVAL";
	public static final String MODEL = "MODEL";
	public static final String NAME = "NAME";
	public static final String OIDCARD = "OIDCARD";
	public static final String OPERATIONS = "OPERATIONS";
	public static final String OWNER = "OWNER";
	public static final String RESUME_DATE = "RESUME_DATE";
	public static final String REVOKE_DATE = "REVOKE_DATE";
	//public static final String ATTRIBUTES = "ATTRIBUTES";
	public static final String REVOKE_STATUS = "REVOKE";
	public static final String SECLABEL = "SECLABEL";
	public static final String SECLEVEL = "SECLEVEL";
	public static final String UAUDIT = "UAUDIT";
	public static final String WHEN_DAYS = "WHEN.DAYS";
	public static final String WHEN_TIME = "WHEN.TIME";
	public static final String INFO_INTERVAL = "INFO.INTERVAL";
	public static final String INFO_CREATE_DATE = "INFO.CREATE_DATE";
	public static final String INFO_LAST_LOGIN_DATE = "INFO.LAST_LOGIN_DATE";
	public static final String INFO_PASSCHG_DATE = "INFO.PASSCHG_DATE";
	public static final String INFO_UNKNOWNCAT = "INFO.UNKNOWNCAT";
	public static final String NOCICS = "NOCICS";
	public static final String CICS_OPCLASS = "CICS.OPCLASS"; // Multi-Valued...
	public static final String CICS_OPPRTY = "CICS.OPPRTY";
	public static final String CICS_TIMEOUT = "CICS.TIMEOUT";
	public static final String CICS_XRFSOFF = "CICS.XRFSOFF";
	public static final String NODFP = "NODFP";
	public static final String DFP_DATAAPPL = "DFP.DATAAPPL";
	public static final String DFP_DATACLAS = "DFP.DATACLAS";
	public static final String DFP_MGMTCLAS = "DFP.MGMTCLAS";
	public static final String DFP_STORCLAS = "DFP.STORCLAS";
	public static final String NOLANGUAGE = "NOLANGUAGE";
	public static final String LANGUAGE_PRIMARY = "LANGUAGE.PRIMARY";
	public static final String LANGUAGE_SECONDARY = "LANGUAGE.SECONDARY";
	public static final String NOOPERPARM = "NOOPERPARM";
	public static final String OPERPARM_ALTGRP = "OPERPARM.ALTGRP";
	public static final String OPERPARM_AUTH = "OPERPARM.AUTH";// Multi-Valued...
	public static final String OPERPARM_AUTO = "OPERPARM.AUTO";
	public static final String OPERPARM_CMDSYS = "OPERPARM.CMDSYS";
	public static final String OPERPARM_DOM = "OPERPARM.DOM";
	public static final String OPERPARM_KEY = "OPERPARM.KEY";
	public static final String OPERPARM_LEVEL = "OPERPARM.LEVEL";
	public static final String OPERPARM_LOGCMDRESP = "OPERPARM.LOGCMDRESP";
	public static final String OPERPARM_MFORM = "OPERPARM.MFORM"; // Multi-Valued...
	public static final String OPERPARM_MIGID = "OPERPARM.MIGID";
	public static final String OPERPARM_MONITOR = "OPERPARM.MONITOR"; // Multi-Valued...
	public static final String OPERPARM_MSCOPE = "OPERPARM.MSCOPE";// Multi-Valued...
	public static final String OPERPARM_ROUTCODE = "OPERPARM.ROUTCODE";// Multi-Valued...
	public static final String OPERPARM_STORAGE = "OPERPARM.STORAGE";
	public static final String OPERPARM_UD = "OPERPARM.UD";
	public static final String NOTSO = "NOTSO";
	public static final String TSO_ACCTNUM = "TSO.ACCTNUM";
	public static final String TSO_COMMAND = "TSO.COMMAND";
	public static final String TSO_DEST = "TSO.DEST";
	public static final String TSO_HOLDCLASS = "TSO.HOLDCLASS";
	public static final String TSO_JOBCLASS = "TSO.JOBCLASS";
	public static final String TSO_MSGCLASS = "TSO.MSGCLASS";
	public static final String TSO_PROC = "TSO.PROC";
	public static final String TSO_SECLABEL = "TSO.SECLABEL";
	public static final String TSO_SYSOUTCLASS = "";
	public static final String TSO_UNIT = "TSO.UNIT";
	public static final String TSO_USERDATA = "TSO.USERDATA";
	public static final String NOWORKATTR = "NOWORKATTR";
	public static final String WORKATTR_WAADDR1 = "WORKATTR.WAADDR1";
	public static final String WORKATTR_WAADDR2 = "WORKATTR.WAADDR2";
	public static final String WORKATTR_WAADDR3 = "WORKATTR.WAADDR3";
	public static final String WORKATTR_WAADDR4 = "WORKATTR.WAADDR4";
	public static final String WORKATTR_WABLDG = "WORKATTR.WABLDG";
	public static final String WORKATTR_WADEPT = "WORKATTR.WADEPT";
	public static final String WORKATTR_WANAME = "WORKATTR.WANAME";
	public static final String WORKATTR_WAROOM = "WORKATTR.WAROOM";
	public static final String NOOMVS = "NOOMVS";
	public static final String OMVS_UID = "OMVS.UID";
	public static final String OMVS_HOME = "OMVS.HOME";
	public static final String OMVS_PROGRAM = "OMVS.PROGRAM";
	public static final String OMVS_ASSIZEMAX = "OMVS.ASSIZEMAX";
	public static final String OMVS_CPUTIMEMAX = "OMVS.CPUTIMEMAX";
	public static final String OMVS_FILEPROCMAX = "OMVS.FILEPROCMAX";
	public static final String OMVS_MMAPAREAMAX = "OMVS.MMAPAREAMAX";
	public static final String OMVS_PROCUSERMAX = "OMVS.PROCUSERMAX";
	public static final String OMVS_THREADSMAX = "OMVS.THREADSMAX";
	public static final String NOLNOTES = "NOLNOTES";
	public static final String LNOTES_SNAME = "LNOTES.SNAME";
	public static final String NONDS = "NONDS";
	public static final String NDS_UNAME = "NDS.UNAME";
	public static final String NONETVIEW = "NONETVIEW";
	public static final String NETVIEW_CONSNAME = "NETVIEW.CONSNAME";
	public static final String NETVIEW_CTL = "NETVIEW.CTL";
	public static final String NETVIEW_DOMAINS = "NETVIEW.DOMAINS";
	public static final String NETVIEW_IC = "NETVIEW.IC";
	public static final String NETVIEW_MSGRECVR = "NETVIEW.MSGRECVR";
	public static final String NETVIEW_NGMFADMN = "NETVIEW.NGMFADMN";
	public static final String NETVIEW_NGMFVSPN = "NETVIEW.NGMFVSPN";
	public static final String NETVIEW_OPCLASS = "NETVIEW.OPCLASS";// Multi-Valued...
	public static final String NODCE = "NODCE";
	public static final String DCE_AUTOLOGIN = "DCE.AUTOLOGIN";
	public static final String DCE_DCENAME = "DCE.DCENAME";
	public static final String DCE_HOMECELL = "DCE.HOMECELL";
	public static final String DCE_HOMEUUID = "DCE.HOMEUUID";
	public static final String DCE_UUID = "DCE.UUID";
	public static final String NOOVM = "NOOVM";
	public static final String OVM_FSROOT = "OVM.FSROOT";
	public static final String OVM_HOME = "OVM.HOME";
	public static final String OVM_PROGRAM = "OVM.PROGRAM";
	public static final String OVM_UID = "OVM.UID";
	public static final String NODCERT = "NODCERT";
	public static final String DCERT_SERIAL_2 = "DCERT.SERIAL.2";
	public static final String DCERT_CREATE_DATE_2 = "DCERT.CREATE_DATE.2";
	public static final String DCERT_OWNER_2 = "DCERT.OWNER.2";
	public static final String DCERT_SERIAL_NUMBER_2 = "DCERT.SERIAL_NUMBER.2";
	public static final String DCERT_ISSUER_NAME_2 = "DCERT.ISSUER_NAME.2";
	public static final String DCERT_TRUST_2 = "DCERT.TRUST.2";
	public static final String DCERT_SUBJECT_NAME_2 = "DCERT.SUBJECT_NAME.2";
	public static final String DCERT_VALID_NOT_BEFORE_2 = "DCERT.VALID_NOT_BEFORE.2";
	public static final String DCERT_VALID_NOT_AFTER_2 = "DCERT.VALID_NOT_AFTER.2";
	public static final String DEF_UG_NAME_OLD = "DEF_UG_NAME_OLD";
	public static final String LAST_ACCESS = "LAST_ACCESS";
	public static final String PROXY_LDAPHOST = "PROXY.LDAPHOST";
	public static final String PROXY_BINDDN = "PROXY.BINDDN";
	public static final String PROXY_BINDPW = "PROXY.BINDPW";
	public static final String PASSWORD = "PASSWORD";
	public static final String PWD_LIFE = "PWD_LIFE";
	public static final String PASSDATE = "PASSDATE";
	public static final String LIMIT_DEBIT = "LIMIT_DEBIT";
	public static final String LIMIT_CREDIT = "LIMIT_CREDIT";

}
